workflows:
  build-android:
    name: Build Android APK (Free)
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.findyourride.app"
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - findyourrideapp@gmail.com
